apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: keptnsandbox/keptn-service-template-python # Todo: Replace this with your image name
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - deploy/service.yaml
